"use strict";

module.exports = [
    "You know, if there were gangs around like in the old days, I'd be running things, not you.",
    "I'll be taking these Huggies and whatever cash ya got.",
    "I don't know if I started drinking 'cause my wife left me but fuck it anyway.",
    "This is a snakeskin jacket!",
    "Did I ever tell ya that this here jacket represents a symbol of my individuality, and my belief in personal freedom?",
    "I want to take his face… off.",
    "I could eat a peach for hours.",
    "If I were to let you suck my tongue, would you be grateful?",
    "If you dress like Halloween, ghouls will try to get in your pants.",
    `You watch your FUCKIN' MOUTH! I'm about to unleash the biblical plague "Hell-A" deserves. But I'll give this SHITHOLE a break if my brother and I walk.`,
    "I would rather have had one touch of her hand than eternity without it.",
    "Let's ride!",
    "Put… the bunny… back… in the box.",
    "I have always found something in life worth singing about and for that I cannot apologize.",
    "I've seen every possible ending.",
    "There are only two tragedies in life. One is not getting what you want, the other is getting it.",
    "You… kept me… alive.",
    "I lost my hand! I lost my bride!",
    "I'm gonna steal the Declaration of Independence!",
    "Bugle Boy, me Jesse James!",
    "You are what you love, not what loves you.",
    "I want that cake!",
    "Balls. Attitude. Direction.",
    "I have an acronym for myself. Know what it is? B.A.D. B.A.D... Balls, Attitude, Direction. You should give yourself an acronym... 'cause it helps you visualize your goals.",
    "I AM THE GREATEST!",
    "And Tess… Get in the god damn chair.",
    "I'm gonna kidnap the President of the United States.",
    "People don't throw things at me any more. Maybe because I carry a bow around.",
    "I mean, I'll bet no one ever threw a pie at, like Harriet Tubman, the founder of the Underground railroad. I'll bet you a million fucking dollars.",
    "I'm a vampire! I'm a vampire! I'm a vampire!",
    "A, B, C, D, E, F, G! H, I, J, K, L, M, N, O, P!  Q, R, S, T, U, V! W, X, Y, Z! HUH? THAT'S ALL YOU HAVE TO DO!",
    "I NEVER MISFILED ANYTHING! NOT ONCE, NOT ONE TIME! I wanna know, really, WHO DID?",
    "Am I getting THROUGH TO YOU, Alva?",
    "You just PUT it IN the RIGHT FILE! According to ALPHABETICAL ORDER!",
    "Hey have you ever been dragged to the sidewalk and beaten till you PISSED… BLOOD!",
    "DIE! FUCKER DIE! DIE!",
    "Where are the Band-Aids? This IS an ambulance, isn't it?",
    "Who gives a shit if you're sorry?",
    "I just stole fifty cars in one night!",
    "OH, NO! NOT THE BEES! NOT THE BEES!",
    "WH-WHAT IS THAT? WHAT IS THAT? WHAT IS IT?",
    "How'd it get burned? How'd it get burned? HOW'D IT GET BURNED, HOW'D IT GET BURNED?",
    "THIS IS MURDER! *MURDER!* YOU'LL ALL BE *GUILTY!* AND YOU'RE DOING IT FOR *NOTHING!* KILLING ME WON'T BRING BACK YOUR GODDAMN HONEY!",
    "BITCHES! YOU BITCHES!",
    "What's in the bag? A shark or something?",
    "Step away from the bike!",
    "How in the name of ZEUS'S BUTTHOLE did you get out of your cell?",
    "Curse you, rock, a curse upon your children!",
    "Yeah, girls mature faster than guys.",
    "Adios, Red Rock.",
    "My dog barks some.",
    "Decaf, please. I've reached my target heart rate for the day.",
    "Shoot him again! His soul's still dancing!",
    "What a magical heap of Navajo horseshit!",
    "Yoohoo! Can I get a room?",
    "Where there's money, there's competition and the guy paying me usually wins.",
    "Brad, your sister's turning into a fox!",
    "I think shit just happens. But that's me.",
    "It's going to make him perfect, PERFECT!",
    "All right, but when they attack the car, save the radio.",
    "She looks totally dazzling tonight.",
    "I'm a mole. I got a thing for worms.",
    "Whomever slays the most men drinks for free.",
    "Oh, child… You always knock me for a loop!",
    "Ring Dings and milk? Oh sure. Then we'll get some balloons and go to the puppet show.",
    "I had a dream. You were insulting me, Dave. Repeatedly",
    `Now I know why Mother calls you "a natural born whore."`,
    "I know for all your talk, you're about the whitest damn black man I ever met.",
    "Fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuck!",
    "Ooooohhhhh!",
    "I wanna shake you naked and eat you alive…",
    "Let me tell you something, people die, people die, everybody dies, so leave him!",
    "What's he gonna do? Not let me back in?",
    "You mean America's high-flyin' red-white-and-blue bird of freedom?",
    "Eat bark, shithead!",
    "Tomorrow isn't a place. It's-it's-it… Ugh! You can't see it!",
    "I thought I was a man already.",
    "In your hands they go back to being nothing but rocks.",
    "Wanna smoke?",
    "You will tell me or I will eat your stinking soul!",
    "He just scratched the surface and I thought someone should finish it.",
    "That makes me sound like some kind of fancy boy!",
    "I'll look like a fancy boy.",
    "You think I'm queer in the attic.",
    "She's foolish for me.",
    "Is anybody hurt? Can I give somebody a lift?",
    "That was for the eight years in prison.",
    "You know, he stalks them like his next trophy animal, he rapes them and kills them.",
    "I know you all want answers, and believe me, so do I.",
    "How deep is hell?",
    "I'm gonna make sure these bastards pay for what they've taken from you.",
    "THIS IS MY VTTSTAHHHHHH! AHAHAHAHAHA! AHAHAHAHA!",
    "You want my blood?",
    "You've got your head so far up Obama's ass that all you can see is his shit any more.",
    "I think that guy is getting a hand job.  He's still eating so it's hard to tell.",
    "I like to drink egg creams and I like to fight Nazis. A lot.",
    `Don't you think I look a little like Nic Cage in "Con Air"?`,
    "Once you have money, you're never 100 percent sure who your friends are.",
    "YOU OWE ME!",
    "I was going to grab life by the balls and squeeze.",
    "I be bangin'",
    "Don't make me take off my sunglasses.",
    "Sawzall.  It saws all.",
    "My mom says Katie gives her the willies.",
    "Titans, you guys are never doing anything actually heroic.",
    "You kill my cat? I'll blow your head off.",
    "The universe has given me a second chance.",
    "Scores have to be settled.",
    "You have gambled. You have lost. It's over.",
    "It wasn't like any color I've seen before.",
    "$20,000. That's what I'm gonna pay ya to kill my wife.",
    "You ain't gonna fly any more than I could, Birdy.",
    "Pay the what?",
    "Nothing. There's nothing I can do and I hate it.",
    "Hey, there you go. You look like a million bucks. You feel better now?",
    "Maybe life is shitty. It is shitty. I'll tell you something. I'm not trying to pin life anymore. I don't even fucking understand it.",
    "I come for the Reaper!",
    "That was my favorite shirt.",
    "You are a vicious snowflake.",
    "You ripped my shirt! YOU RIPPED MY SHIRT!",
    "I'm your God now!",
    "What do you say, we cut the chit-chat, a-hole!",
    "We're gonna need more holy water.",
    "Snort that, suckers!",
    "It means… you're both gonna die.",
    "Your God or mine?",
    "That’s funny, my name’s Roger. Two Rogers don’t make a right.",
    "Well Hoorah for the sounds of fucking silence.",
    "And the whole time… you stand there… with this who-me… expression… on your FACE!",
    "Cause I was made for this sewer Baby and I AM the king",
    "Cause obviously you have a tendency to OVERREACT!",
    "Well, I'm one of those fortunate people who like my job, sir. Got my first chemistry set when I was seven, blew my eyebrows off, we never saw the cat again, been into it ever since.",
    "Sorry boss, but there's only two men I trust. One of them's me. The other's not you.",
    "Only if it's a noun, and the words have equal weight. Like, Homeland Security. If it's a participle modifying the first word, then… you better keep it lower case.",
    "What do you think I'm gonna do? I'm gonna save the fuckin' day!",
    "You don't have a lucky crack pipe?",
    "Guns and wine. Naughty priests.",
    "Fuck you, trailer trash!",
    "You'll be seeing a lot of changes around here. Papa's got a brand new bag.",
    "Tool up, honey bunny. It's time to get bad guys.",
    "I saw you and you saw me, don’t pretend like you don’t know who I am girly man",
    "Everything I take is prescription - except for the heroin.",
    "Bangers and mash! Bubbles and squeak! Smoked eel pie! Haggis!",
    "l guess they don't call you the Executioner for nothing! And you sign my kid's autograph!",
    `Listen, I think we got started off on the wrong foot. I'm Stan Goodspeed, FBl. Uh - Let's talk music. Do you like the Elton John song, "Rocket Man"?`,
    "Well, today's your lucky day, 'cause I brought an eagle.",
    "Release the baby!",
    "I love pressure. I eat it for breakfast.",
    "I just remembered, I have to go into town to pick up your anti-itch cream",
    "What are these fuckin' iguanas doing on my coffee table?",
    "I mean it, honey, the world is being Fed-exed to hell in a hand cart.",
    "Black, French, alcoholic priest, kind of a dick. Why, do you know him?",
    "I never disrobe before gunplay.",
    "Hey. Dirtbag",
    "The snowflakes are perfect. The stars are perfect. Not us. Not us! We are here to ruin ourselves and to break our hearts and love the wrong people and die. The storybooks are *bullshit*. Now I want you to come upstairs with me and get in my bed!",
    "What's that like? What's it taste like? Describe it like Hemingway",
    "I told you I'd share my ticket. I never planned on sharing my heart. Maybe I could get lucky twice today.",
    "What did I do? You fuck with the bull, you get the horns. That's what I did.",
    "After the Cold War, the AK-47 became Russia's biggest export. After that came vodka, caviar, and suicidal novelists.",
    "It's like we're on two different channels now. I'm CNN and she's the Home Shopping Network.",
];
